#!/usr/bin/env bash
set -e

if [[ -z "$1" ]]; then
    echo "Error: No argument provided. Use 'gh gitignore --help' for usage instructions."
    exit 1
fi

if [[ "$1" == "--help" ]]; then
    echo "Usage: gh gitignore [COMMAND] [OPTIONS] [TEMPLATE]"
    echo ""
    echo "Commands:"
    echo "  add         Adds .gitignore from template in https://github.com/github/gitignore"
    echo "  list        Lists all template in https://github.com/github/gitignore"
    echo "  search      Search template in https://github.com/github/gitignore"
    echo ""
    echo "Options:"
    echo "  --append    Append template to .gitignore, replaces when not passed"
    echo "  --help      Displays halp"
    echo ""
    echo "Examples:"
    echo "  gh gitignore Python  # Add Python .gitignore"
    echo "  gh gitignore add Global/VisualStudioCode --append  # Append VSCode to .gitignore"
    echo "  gh gitignore list  # List templates"
    echo "  gh gitignore search python  # Search for all 'python' templates"
    exit 0
fi

if [[ "$1" == "add" ]]; then
    if [[ "$2" == "--append" ]]; then
        if [[ -z "$3" ]]; then
            echo "Error: No argument provided for [template]."
            echo "Use 'gh gitignore add --append [template]' to append [template] to current .gitignore."
            exit 1
        fi

        # Download template and append it to .gitignore
        file_url="https://raw.githubusercontent.com/github/gitignore/main/$3.gitignore"
        echo "[INFO] fetching template $3 from $file_url"
        curl $file_url -s -o - >> .gitignore
    else
        # Download template and replace .gitignore with it
        file_url="https://raw.githubusercontent.com/github/gitignore/main/$2.gitignore"
        echo "[INFO] fetching template $2 from $file_url"
        curl $file_url -s -o - > .gitignore
    fi
fi


if [[ "$1" == "list" ]]; then
    # Download template and replace .gitignore with it
    search_url="https://api.github.com/repos/github/gitignore/git/trees/main?recursive=1"
    echo "[INFO] listing templates from $search_url"
    curl $search_url -s | jq '.tree[] | .path' | grep -i -E '\.gitignore\"$'
fi


if [[ "$1" == "search" ]]; then
    # Download template and replace .gitignore with it
    search_url="https://api.github.com/repos/github/gitignore/git/trees/main?recursive=1"
    echo "[INFO] searching for $2 in $search_url"
    curl $search_url -s | jq '.tree[] | .path' | grep -i -E '\.gitignore\"$' | grep -i -E $2
fi
